apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:ronaldmanganaro/TCGScraper.git
    path: k8s/charts/traefik
    targetRevision: feature-DeployStreamlitArgocd
    helm:
      valuesFiles:
        - ../chart/traefik/traefik-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

