apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tcg-toolkit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: git@github.com:ronaldmanganaro/TCGScraper.git
    path: k8s/tcg-toolkit
    targetRevision: feature-IngressController
  destination:
    server: https://kubernetes.default.svc
    namespace: streamlit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
