apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: 28.1.0
    helm:
      releaseName: traefik
      values: |
        certificatesResolvers:
          letsencrypt:
            acme:
              email: ronaldmanganaro@gmail.com
              storage: /data/acme.json
              httpChallenge:
                entryPoint: web
        persistence:
          enabled: true
          size: 128Mi
          accessModes:
            - ReadWriteOnce
          mountPath: /data
        dashboard:
          enabled: true
          ingressRoute:
            enabled: true
            entryPoints:
              - web
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
