services:

  streamlit:
    container_name: streamlit
    build: 
      context: ../
      dockerfile: docker/Dockerfile.streamlit-dev
    image: rmangana/streamlit:latest
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi:
    container_name: fastapi
    image: rmangana/fastapi:latest
    volumes:
      - ../fastapi:/fastapi 
    build:
      context: ../
      dockerfile: docker/Dockerfile.fastapi-dev
    ports:
      - "80:80"
    env_file:
      - .env

  db:
    container_name: TCGPlayerDB
    image: rmangana/tcgplayerdb:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile.db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    ports: 
      - "5432:5432"
    volumes:
      - $VOLUME_PATH:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "rmangana"]
      interval: 10s
      timeout: 5s
      retries: 5