FROM python:3.10-slim

WORKDIR /fastapi

RUN apt-get update && apt-get install -y \
    poppler-utils \
    vim \
    && rm -rf /var/lib/apt/lists/*

COPY /fastapi/requirements.txt /fastapi/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /fastapi/requirements.txt

COPY fastapi /fastapi

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]

# If running behind a proxy like Nginx or Traefik add --proxy-headers
# CMD ["fastapi", "run", "app/main.py", "--port", "80", "--proxy-headers"]