FROM python:3.10-slim

ENV PYTHONUNBUFFERED=1

# Install the AWS CLI dependencies
RUN apt-get update && apt-get install -y \
    curl \
    unzip \
    python3-dev \
    libpq-dev \
    poppler-utils \
    vim \
    git \
    && rm -rf /var/lib/apt/lists/*

# Fixes line endings for git on Windows
RUN git config --global core.autocrlf input

# Install AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm awscliv2.zip

# Install Python dependencies
COPY . /TCGScraper
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r /TCGScraper/streamlit/requirements.txt

# Install the required browser binaries
RUN playwright install --with-deps

USER root

ENV AWS_ACCESS_KEY_ID AKIAR4PHQSUDHT5QEYOE
ENV AWS_SECRET_ACCESS_KEY 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
ENV AWS_DEFAULT_REGION us-east-1

EXPOSE ${SERVER_PORT}
ENTRYPOINT ["sh", "-c", "streamlit run /TCGScraper/streamlit/app.py --server.port ${SERVER_PORT} --server.headless true"]