apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tcg-database
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:ronaldmanganaro/TCGScraper.git
    path: k8s/applications/tcg-database
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: streamlit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true