apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  finalizers:
    # best practice: use background cascading deletion when destroyOnFinalize is enabled.
    - resources-finalizer.argocd.argoproj.io/background
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
  project: default
  source:
    repoURL: "https://github.com/my-repo/my-app.git"
    path: "./deploy"  # the location of the Stack maifest
    targetRevision: main