apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streamlit-ingress
  namespace: streamlit
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: streamlit-stickyheader-middleware@kubernetescrd
spec:
  rules:
  - host: tcg-toolkit.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: streamlit-service
              port:
                number: 8501
