[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "xxx"
client_id = "481144915731-8pljikcdpitkirnbu60eptrsfd87be52.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"  # fmt: skip