name: Deploy Latest

on:
  workflow_dispatch:
  push:
    branches: 
      - '*'

jobs:
  deploy-ec2:
      runs-on: ec2
      steps:
        - name: Checkout code with authentication
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.CM_PAT }}
            sparse-checkout: |
              docker/Dockerfile.streamlit
              docker/docker-compose-streamlit.yml
            sparse-checkout-cone-mode: false

        - name: Create .env file
          run: |
            echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> docker/.env
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> docker/.env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> docker/.env
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> docker/.env
            echo "VIRTUAL_HOST=${{ secrets.VIRTUAL_HOST }}" >> docker/.env
            echo "LETSENCRYPT_HOST=${{ secrets.LETSENCRYPT_HOST }}" >> docker/.env
            echo "LETSENCRYPT_EMAIL=${{ secrets.LETSENCRYPT_EMAIL }}" >> docker/.env
            echo "VOLUME_PATH=/home/ubuntu/postgres" >> docker/.env

        - name: Deploy Latest Version of Streamlit with Compose
          run: |
            cd docker
            docker compose -f docker-compose-streamlit.yml down --remove-orphans
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/streamlit:latest
            docker compose -f docker-compose-streamlit.yml up streamlit -d --no-build
