name: Docker Image CI

on:
  push:
    branches: 
      - '*'
  
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Build app Docker image
      run: |
        $tag = "rmangana/pricetracker:$(Get-Date -Format 'yyyyMMddHHmmss')"
        docker build . -f docker/Dockerfile.app --tag $tag 
   
    - uses: actions/checkout@v4
    - name: Build db docker image
      run: |
        $tag = "rmangana/pricetrackerdb:$(Get-Date -Foramt 'yyyyMMddHHmmss')"
        docker build . -f docker/Dockerfile.db --tag $tag