name: Docker Image CI

on:
  push:
    branches: 
      - '*'
  
jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        $tag = "tcgpricetracker:$(Get-Date -Format 'yyyyMMddHHmmss')"
        docker build . --file Dockerfile --tag $tag
