name: Continious Deployment

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'docker/docker.ai'
      - 'streamlit/**'

jobs:
  filter:
    runs-on: self-hosted
    outputs:
      ai: ${{ steps.filter.outputs.ai }}
      streamlit: ${{ steps.filter.outputs.streamlit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Filter paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            ai:
              - 'docker/docker.ai'
            streamlit:
              - 'streamlit/**'

  build-streamlit:
    needs: filter
    if: needs.filter.outputs.streamlit == 'true'
    runs-on: self-hosted
    steps:
    - name: Checkout code with authentication
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.CM_PAT }}

    - name: Create .env file
      run: |
        echo "SERVER_PORT=80" > docker/.env
        echo "VOLUME_PATH=./streamlit" >> docker/.env
    
    - name: Build Docker image
      run: |
        tag="rmangana/streamlit:latest"
        docker build --no-cache . -f docker/Dockerfile.streamlit --tag $tag 
    
    - name: Upload streamlit image to Dockerhub
      run: |
        tag="rmangana/streamlit:latest"
        echo "${{ secrets.DOCKERHUB_PAT }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME}}" --password-stdin
        docker push $tag

  deploy-ec2:
    needs: build-streamlit
    if: needs.build-streamlit.result == 'success'
    runs-on: self-hosted
    steps:
    - name: Checkout code with authentication
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.CM_PAT }}
        sparse-checkout: |
          docker/Dockerfile.streamlit
          docker/docker-compose.yml
        sparse-checkout-cone-mode: false
    
    - name: Deploy Latest Version of Streamlit
      run: |
        echo "OLLAMA_VOLUME_PATH=/home/ubuntu/ollama" >> /home/ubuntu/TCGScraper/docker/.env
        docker rm -f streamlit
        docker system prune -af
        docker pull rmangana/streamlit:latest
        docker compose up streamlit -d --no-build

