name: Continious Deployment

on:
  workflow_dispatch:
    inputs:
      skip_to_deploy:
        description: 'Skip all steps except deploy-ec2'
        required: false
        default: 'false'
        type: choice
        options:
          - 'false'
          - 'true'
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'docker/docker.ai'
      - 'streamlit/**'

jobs:
  filter:
    runs-on: self-hosted
    outputs:
      ai: ${{ steps.filter.outputs.ai }}
      streamlit: ${{ steps.filter.outputs.streamlit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Filter paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            ai:
              - 'docker/docker.ai'
            streamlit:
              - 'streamlit/**'

  build-streamlit:
    needs: filter
    if: needs.filter.outputs.streamlit == 'true' && github.event.inputs.skip_to_deploy != 'true'
    runs-on: rgbtower
    steps:
    - name: Checkout code with authentication
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.CM_PAT }}
        ref: main

    - name: Create .env file
      run: |
        echo SERVER_PORT=${{ secrets.SERVER_PORT }} >>  docker\.env
      shell: cmd

    - name: Build Streamlit Docker image with Compose
      run: |
        cd docker
        docker compose -f docker\docker-compose-streamlit.yml build streamlit

    - name: Log in to DockerHub
      run: echo %DOCKERHUB_PAT% | docker login -u "%DOCKERHUB_USERNAME%" --password-stdin
      shell: cmd
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PAT: ${{ secrets.DOCKERHUB_PAT }}

    - name: Push Streamlit image to DockerHub
      run: |
        docker tag streamlit ${{ secrets.DOCKERHUB_USERNAME }}/streamlit:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/streamlit:latest
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

  deploy-ec2:
    needs: build-streamlit
    if: (needs.build-streamlit.result == 'success' && (github.event.inputs.skip_to_deploy != 'true' || github.event.inputs.skip_to_deploy == null)) || github.event.inputs.skip_to_deploy == 'true'
    runs-on: ec2
    steps:
    - name: Checkout code with authentication
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.CM_PAT }}
        sparse-checkout: |
          docker/Dockerfile.streamlit
          docker/docker-compose-streamlit.yml
        sparse-checkout-cone-mode: false
    
    - name: Create .env file
      run: |
        echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >>  docker/.env
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >>  docker/.env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >>  docker/.env
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >>  docker/.env
        echo "VIRTUAL_HOST=${{ secrets.VIRTUAL_HOST }}" >>  docker/.env
        echo "LETSENCRYPT_HOST=${{ secrets.LETSENCRYPT_HOST }}" >>  docker/.env
        echo "LETSENCRYPT_EMAIL=${{ secrets.LETSENCRYPT_EMAIL }}" >> docker/.env
        echo "VOLUME_PATH=/home/ubuntu/postgres" >> docker/.env


    - name: Deploy Latest Version of Streamlit with Compose
      run: |
        cd docker
        docker compose -f /docker/docker-compose-streamlit.yml down --remove-orphans
        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/streamlit:latest
        docker compose -f /docker/docker-compose-streamlit.yml up streamlit -d --no-build
